tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "asdf"
brew "direnv"
brew "ffmpeg"
brew "firebase-cli"
brew "gh"
brew "gitmoji"
brew "grpc"
brew "imagemagick"
brew "jq"
brew "mas"
brew "mint"
brew "terraform"
brew "tree"
brew "yarn"
brew "yq"
cask "appcleaner"
cask "brave-browser"
cask "charles"
cask "cyberduck"
cask "deepl"
cask "discord"
cask "docker"
cask "figma"
cask "gitify"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "jetbrains-toolbox"
cask "kindle"
cask "notion"
cask "openvpn-connect"
cask "postman"
cask "proxyman"
cask "rectangle"
cask "sf-symbols"
cask "skitch"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "xcodes"
cask "zoom"

mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
