tap "homebrew/bundle"
tap "xcodesorg/made"
brew "asdf"
brew "buf"
brew "direnv"
brew "firebase-cli"
brew "gh"
brew "grpc"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "stern"
brew "terraform"
brew "tree"
cask "appcleaner"
cask "charles"
cask "chatgpt"
cask "cursor"
cask "deepl"
cask "discord"
cask "docker"
cask "figma"
cask "gitify"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "jetbrains-toolbox"
cask "postman"
cask "rectangle"
cask "shottr"
cask "slack"
cask "spotify"
cask "tradingview"
cask "xcodes"
cask "zoom"
mas "CopyLinkToPasteboard", id: 1551527433
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
